### ISSUE TITLE
Belongs to relationship is always null even though ID is present

### ISSUE THREAD

**Issue by ezekg** [danielspaniel/ember-data-change-tracker#8] opened 2017-03-02 17:11 UTC
Using the `keepOnlyChanged` serializer mixin, with auto tracking enabled.

```javascript
var ENV = {
  // …
  changeTracker: { trackHasMany: true, auto: true },
  // …
}
```

```javascript
import DS from 'ember-data'

export default DS.Model.extend({
  product: DS.belongsTo('product')
})
```

When logging the tracker initialization, it looks like the serialization for every belongs to relationship returns `null`, because `model.belongsTo(rel).value()` returns `null`. I can work around this by updating the belongs to serializer utility to use `model.belongsTo(rel).id()`, which oddly returns the correct ID, but doesn't account for polymorphic relationships:

```javascript
// ember-data-change-tracker/addon/utilities.js

export const relationShipTransform = {
  belongsTo: {
    serialize(model, key, options) {
      let value = model.belongsTo(key).id();
      return value;
    },

    deserialize() {
    }
  },
  // …
}
```

I have a few polymorphic relationships, so in the end, this isn't going to work. The real question I can't figure out is why `value()` returns `null`, yet `id()` returns the correct ID. Is it maybe [because the relationship is not fully loaded](https://github.com/emberjs/data/blob/08b04621c0c654f746c8e148d25bb7668a553bd3/addon/-private/system/references/belongs-to.js?ts=2#L317)?

Belongs to relationship data is returned like this via the JSON API, including with linkage (type+id) as well as a related link:

```json
"relationships": {
  "product": {
    "links": {
      "related": "/v1/users/0b4b1a9a-e25a-4f14-a95e-d9dd378d6065/product"
    },
    "data": {
      "type": "products",
      "id": "3ab38aae-bbf7-4846-9c32-af9d94bf5ad4"
    }
  }
}
```

Ember and Ember data are up to date. Using latest version of this package as well.

Any ideas?

**Comment by danielspaniel** [comment] 2017-03-02 18:01
I guess it depends on what is going on. 
Right now, the change tracker is saying the relationship is null ( when it's not loaded , even though it knows the id it needs to fetch it ). 
 So can you explain exactly what the issue is with this.  
  I know what you are talking about, but you did not say why it is a problem => exactly.

**Comment by ezekg** [comment] 2017-03-02 19:27
Sorry, I didn't make the problem clear. I'd like to track changes, or in my case the lack of changes, to the relationship so that it is not included in `PATCH` update payloads (via `keepOnlyChanged` mixin).

Right now, the relationship is always marked as dirty because the previous state is `null`, when in reality, it's not `null` and the ID + type of the relation is available via the linkage data (which is all it really needs for a dirty check: `old.id !== new.id || old.type !== new.type`).

How would you suggest I fix this without loading the whole relationship resource? Somewhat new to Ember, so any suggestions would be great.

**Comment by danielspaniel** [comment] 2017-03-02 19:34
This is what I thought but I wanted to hear you confirm it. 
Now, what is so interesting here is that the belongsTo value that is saved is null .. because value is null .. so why ( if you have not fetched anything ) would that change. 
If you see what I mean. 
Change tracker should continue to think the value is null ( regardless of id value ) right? 
So, you start with null, then it is still null == no change 
That is what puzzles me. 
Let me try and make a test for this case with the links and polymorphic and see ..

**Comment by danielspaniel** [comment] 2017-03-02 19:46
And can you explain what edits you are making before you save?  be as exact as you can .. you did not explain that part yet. 
 You start with this data .. I do this or that .. call save ( serialize ) and it sends the product belongsTo value

**Comment by danielspaniel** [comment] 2017-03-02 19:48
My initial test can not verify what you are saying. 
 I think you might have to give me the model and the payload

**Comment by ezekg** [comment] 2017-03-02 19:48
Okay, maybe the issue is cropping up because I'm using an update form that requests the related type's index (in our case, `product`) to populate a `<select>` element to be able to change the relationship to a different resource. So the edits depend on what is changed via the form, and then the edited model is then sent to a route action that performs the save.

So to be clear, the related resource _is_ eventually loaded, and when the form is submitted the tracker compares `null !== loadedId`, which results in a dirty relation, even though the underlying relationship for the model didn't actually change, e.g. the `id` and `type` are still the same.

**Comment by danielspaniel** [comment] 2017-03-02 19:50
Boy am I confused. 
Can I call you on screen hero or something .. i am sick of typing

**Comment by ezekg** [comment] 2017-03-02 20:01
I'm not able to get on a call at the moment. I'll try and get a failing test written tonight and we can start from there. Sorry if my explanation was confusing.

**Comment by danielspaniel** [comment] 2017-03-02 20:02
Oh well .. I almost get what you are saying .. but it is the edit part that is what I don't quite have yet, and the failing test would show me.  So if you can do that I can help out more productively .. thanks.

**Comment by scottwernervt** [comment] 2017-03-03 03:21
@danielspaniel I am also encountering a similar issue with a hasMany relationship being removed when calling `model.rollback()` after all promises are resolved. The hasMany children also have a belongsTo relationship. I created a [ember-twiddle](https://canary.ember-twiddle.com/2bb8a0bf24747e612fbfc8bb4b5d9c4e) to show the issue.

**Comment by danielspaniel** [comment] 2017-03-03 12:51
Thanks for taking the effort to make that twiddle.

 Are you suggesting that when an async relationship  ( belongsTo or hasMany ) resolves (  that the relationship is marked as dirty? Is that the main idea? Want to be 100% sure this what you are pointing out. 
 
 I am a little confused as to when the change tracking starts though. By default change tracker does not track anything unless you configure it to.  You don't have auto track turned on in the environment or in the model and you did not startTracking anywhere .. so that is confusing for me, since if you don't track then changed method would be pretty useless.

**Comment by danielspaniel** [comment] 2017-03-03 13:51
I am wondering if this is a bug at all or just a usage / implementation issue??

The cases details are:
 - any async: true relationship
 - using auto track

So:
 - the main model loads 
   - it has link(s) that points to async models with id's
   - or it has no links at all just empty for now since you have not invoked relationship yet
   - main model thinks it has no relationship(s) 
      - if auto track is on, then null is what is saved for that relationship
 - you load the relationship on the model 
  - checking model.changed() you see that it thinks the relationship changed since it now has the data loaded

Change tracker can not actually solve that problem since the model has no idea what the relationship will hold after async stuff happens. Would require magical abilities I think. 

So, for the case of editing a model and wanting to know what has changed, then you should not use auto track and use model.startTrack() when the model is loaded and you are ready to edit. 

For the case of auto track, that is more tricky and I am not sure that this addon will work then for that situation. How could the tracker know when the relationship is loaded and then "reasses" its saved tracker status. I don't know.  

For @ezekg case with polymorphic relationship with link it is impossible to save the correct information ( id and type ) because the link says the type is "projects" but then the relationship type might actually be "big-project" once it is loaded. 

But it is all back to that same idea. How would the tracker know when the async is finished loading so that it could update the actual base state of the relationships it has saved.  In @ezekg case, you start editing even before that model is loaded.  

I just don't know how to fix this situation. A bit stumped.

**Comment by ezekg** [comment] 2017-03-03 16:10
It's a little messy (not that familiar yet with Ember tests) but here's a failing test:

```javascript
test("touched but unchanged relationships should not serialize when keepOnlyChanged mixin is used", function(assert) {
  let done = assert.async();
  mockSetup({ logLevel: 0 });

  let json = build('project', {
    company: {
      data: { id: '1', type: 'company' }
    }
  });

  mockFindRecord('project').returns({ json });

  Ember.run(() => {
    FactoryGuy.store.find('project', json.get('id')).then((project) => {
      assert.equal(project.belongsTo('company').value(), null, 'relationship should not be loaded');
      assert.equal(project.belongsTo('company').id(), '1', 'relationship record id should be set through linkage');

      // We only want to peek the record, not load it
      mockFindRecord('company').returns({ id: '1' });
      project.startTrack();

      FactoryGuy.store.find('company', '1').then((company) => {
        assert.equal(project.belongsTo('company').id(), company.get('id'), 'ids should match');

        project.set('company', company);
        project.set('title', 'test');

        assert.equal(project.belongsTo('company').id(), company.get('id'), 'ids should still match');

        let { data } = project.serialize();
        let relationships = data.relationships || {};
        let attributes = data.attributes || {};

        assert.ok(relationships.company == null, 'unchanged relationship should not be serialized');
        assert.ok(attributes.title != null, 'changed attribute should be serialized');

        // TODO: Not sure why I need this, but I keep getting the following
        //       error after the tests complete:
        //
        //       Assertion after the final `assert.async` was resolved
        setTimeout(() => {
          mockTeardown();
          done();
        }, 2500);
      });
    });
  });
});
```

If I change the belongsTo serializer to the following, which takes into account relationships that aren't loaded, everything works fine and the failing test passes:

```diff
export const modelTransform = function(model, polymorphic) {
  if (polymorphic) {
-   return { id: model.id, type: model.constructor.modelName };
+   return { id: model.id, type: model.modelName || model.constructor.modelName };
  }
  return model.id;
};

export const relationShipTransform = {
  belongsTo: {
    serialize(model, key, options) {
-     let value = model.belongsTo(key).value();
+     let value = model.belongsTo(key).belongsToRelationship.inverseRecord;
      return value && modelTransform(value, options.polymorphic);
    },

    deserialize() {
    }
  },
  hasMany: {
    serialize(model, key, options) {
      let value = model.hasMany(key).value();
      return value && value.map((item) => modelTransform(item, options.polymorphic));
    },

    deserialize() {
    }
  }
};
```

**Comment by danielspaniel** [comment] 2017-03-03 16:28
Wow .. now that is what I call amazing.  
Not sure how you did that .. but I would most definitely buy you an extra large shot for that fix.

**Comment by scottwernervt** [comment] 2017-03-03 16:38
@ezekg I just verified your patch and rollbacks are now working correctly in my app, thanks!

**Comment by danielspaniel** [comment] 2017-03-03 16:39
thanks for verifying @scottwernervt .. making new version right now

**Comment by ezekg** [comment] 2017-03-03 16:42
Awesome! I'd glad it resolved both issues!

![](http://i.giphy.com/10R53jkO17VQFW.gif)

**Comment by danielspaniel** [comment] 2017-03-03 17:06
closing with new version 
https://github.com/danielspaniel/ember-data-change-tracker/releases/tag/v0.4.2
gotta love that gif .. your hired!

**Closed by danielspaniel** 2017-03-03 17:06 UTC

**Comment by danielspaniel** [comment] 2017-03-03 17:27
Only one reason to stop pouring those drinks ..  
 this fix does not work on ember-data 2.11.1+ , only ember-data 2.10. :(
 Lot's of things changing in ember-data these days, so keep that in mind. 
 I am going to see if I can fix it in ember-data 2.11+  .. and if you have time maybe you can take a crack at it .. you seem to have the magic touch .. ?

**Comment by danielspaniel** [comment] 2017-03-03 17:34
Sorta take that back .. the test breaks up front but continues to work if I take out an assertion. 
So, let me just massage that test a bit to get it under control. 
Since, if you both are using on ember-data 2.11 and ember 2.11+ then it obviously works.

**Comment by ezekg** [comment] 2017-03-03 17:34
Hmm… maybe it's the tests that don't work, because I'm running Ember 2.11.3 and it works fine. It may be the assertion that's expecting the relationship not to be loaded. Maybe the way relationships are loaded changed, idk.

**Comment by ezekg** [comment] 2017-03-03 17:35
That's my bad. I should have initially provided a PR so that the Travis tests would run and I could have caught that.

**Comment by danielspaniel** [comment] 2017-03-03 17:41
it is this one
```javascript
 assert.equal(project.belongsTo('company').value(), null, 'relationship should not be loaded');
```
 with ember-data 2.11.3  this results in a fully materialized model .. interestingly enough.

**Comment by ezekg** [comment] 2017-03-03 17:50
That's odd. I can't find anything in the change log that would explain why that is. I mean the store only has an id and type, so I can't see how it could have an entire record. I'll try and dig in more later on today if I can.

**Comment by scottwernervt** [comment] 2017-03-03 17:50
I am running ember-source  2.11.1 and ember-data 2.11.1. In addition. I believe `hasMany` should be changed to: 

```javascript
let value = model.hasMany(key).hasManyRelationship.members.list;
```

This resolved a rollback issue with one of my nested models which has a hasMany async relationship.

**Comment by danielspaniel** [comment] 2017-03-03 17:53
You want to do a PR with a test for the hasMany @scottwernervt ?
 Hopefully we can get away with a version /tests  that work for all ember-data 2.7+ but if we have to make special version ( 0.5 ) for ember-data 2.11+ I am not opposed to doing that

**Comment by ezekg** [comment] 2017-03-03 20:55
Created a PR to fix my tests (https://github.com/danielspaniel/ember-data-change-tracker/pull/9), but there are still 2 failing tests that are unrelated that I couldn't figure out. It looks like the `build()` function is sideloading dummy data (via included) and creating the relationship records, instead of leaving it as an unloaded relationship.

Maybe something introduced in Ember Data to support nested resource creation for the JSON API spec? Idk enough about FactoryGuy to say, but I've recently seen discussions on that.
